version: '3.1'

services:

  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: hdbpp
      MYSQL_USER: user
      MYSQL_PASSWORD: user_pass
    ports:
      - 3306:3306
    volumes:
      - ./db/data/mysql:/var/lib/mysql
      - ./db/init/mysql:/docker-entrypoint-initdb.d

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_pass
      POSTGRES_DB: bmn_db
    ports:
      - 5432:5432
    volumes:
      - ./db/init/postgres:/docker-entrypoint-initdb.d
      - ./db/data/postgres/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user
      PGADMIN_DEFAULT_PASSWORD: user_pass
    volumes:
      - ./db/data/pgadmin:/var/lib/pgadmin
      - ./db/data/pgadmin/servers.json:/servers.json
    ports:
      - 8081:80

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
